import type { ProblemStatement } from "./types";

export const progressiveProblemStatements: Record<string, ProblemStatement> = {
  "PT-F01-TIME-NORMALIZATION": {
    statement: "Một video có độ dài videoLen và vị trí hiện tại pos, đều ở dạng mm:ss. Lệnh prev lùi 10 giây, next tiến 10 giây; vị trí luôn bị chặn trong [00:00, videoLen]. Nếu vị trí ban đầu hoặc vị trí sau một lệnh nằm trong đoạn opening đóng [opStart, opEnd], trình phát lập tức nhảy tới opEnd. Hãy trả vị trí cuối cùng.",
    officialLinks: [{ label: "[PCCP 기출문제] 1번 — 동영상 재생기", url: "https://school.programmers.co.kr/learn/courses/30/lessons/340213?language=javascript", relation: "EXACT" }],
    input: ["videoLen, pos, opStart, opEnd: chuỗi mm:ss.", "commands: mảng gồm các chuỗi prev hoặc next, xử lý từ trái sang phải."],
    output: "Vị trí cuối ở dạng mm:ss, luôn đủ hai chữ số cho phút và giây.",
    examples: [{ input: `videoLen="10:00", pos="01:30", opening=["01:00","02:00"], commands=[]`, output: `"02:00"`, explanation: "Vị trí ban đầu nằm trong opening nên phải normalize trước lệnh đầu tiên." }],
  },
  "PT-F02-RUN-SCAN": {
    statement: "Một run là đoạn liên tiếp cực đại gồm cùng một ký tự. Với chuỗi text, hãy tìm các chữ cái xuất hiện trong ít nhất hai run tách biệt; số lần xuất hiện bên trong một run không làm tăng số run.",
    officialLinks: [{ label: "PCCP 모의고사 #1 — 외톨이 알파벳", url: "https://school.programmers.co.kr/learn/courses/15008/lessons/121683?language=javascript", relation: "EXACT" }],
    input: ["text: chuỗi chữ thường; chuỗi rỗng được phép."],
    output: "Mảng chữ cái thỏa mãn, sort tăng dần. Nếu không có, trả [\"N\"].",
    examples: [{ input: `text="edeaaabbccd"`, output: `["d","e"]`, explanation: "d và e mỗi chữ xuất hiện ở hai block tách biệt; aaa và cc vẫn chỉ là một run." }],
  },
  "PT-F03-GRID-NEIGHBORS": {
    statement: "Cho grid chữ nhật và một ô hợp lệ (row,col). Hãy liệt kê các tọa độ kề bốn hướng nằm trong grid theo đúng thứ tự trên, dưới, trái, phải. Giá trị trong ô không ảnh hưởng việc là neighbor.",
    officialLinks: [
      { label: "PCCP 모의고사 #2 — 실습용 로봇", url: "https://school.programmers.co.kr/learn/courses/15009/lessons/121687?language=javascript", relation: "RELATED" },
      { label: "PCCP 기출 — 석유 시추", url: "https://school.programmers.co.kr/learn/courses/30/lessons/250136?language=javascript", relation: "RELATED" },
    ],
    input: ["grid: ma trận chữ nhật; có thể rỗng.", "row, col: tọa độ 0-based, hợp lệ khi grid không rỗng."],
    output: "Mảng các cặp [nextRow,nextCol] hợp lệ theo thứ tự directions; grid rỗng trả [].",
    examples: [{ input: "grid=[[0,0,0],[0,0,0]], row=0, col=1", output: "[[1,1],[0,0],[0,2]]", explanation: "Hướng trên ra ngoài; ba hướng còn lại hợp lệ." }],
  },
  "PT-F04-FREQUENCY-MULTISET": {
    statement: "Hai mảng biểu diễn hai multiset: order không quan trọng nhưng số lần xuất hiện của từng value phải giống nhau. Hãy xác định chúng có bằng nhau hay không mà không sort hoặc mutate input. Value có thể là primitive falsy như 0, false hoặc chuỗi rỗng.",
    officialLinks: [{ label: "Bài PCCP nguồn về Set/run — 외톨이 알파벳", url: "https://school.programmers.co.kr/learn/courses/15008/lessons/121683?language=javascript", relation: "RELATED" }],
    input: ["left, right: hai mảng primitive; duplicate mang ý nghĩa multiplicity.", "Hai array có thể rỗng hoặc có độ dài khác nhau."],
    output: "true khi mọi value có cùng multiplicity ở hai mảng; ngược lại false.",
    examples: [{ input: "left=[1,1,2], right=[1,2,2]", output: "false", explanation: "Hai bên có cùng distinct set {1,2}, nhưng multiplicity của 1 và 2 khác nhau." }],
  },
  "PT-F05-MULTIKEY-SORT": {
    statement: "Cho leaderboard gồm các record {id,score,time}. Hãy xếp score giảm dần; nếu bằng score thì time tăng dần; nếu vẫn bằng nhau thì id theo lexical ascending. Trả danh sách id và không thay đổi mảng records ban đầu.",
    officialLinks: [{ label: "Bài PCCP nguồn có output sorting — 외톨이 알파벳", url: "https://school.programmers.co.kr/learn/courses/15008/lessons/121683?language=javascript", relation: "RELATED" }],
    input: ["records: mảng object có id string duy nhất, score Number và time Number.", "Thứ tự input không phải tie-break ngầm."],
    output: "Mảng id theo đúng ba khóa score↓, time↑, id lexical↑.",
    examples: [{ input: `[{id:"a",score:100,time:50},{id:"d",score:100,time:40},{id:"b",score:100,time:40}]`, output: `["b","d","a"]`, explanation: "b,d cùng score/time nên id lexical quyết định; a chậm hơn nên đứng sau." }],
  },
  "PT-F06-ATOMIC-ROBOT": {
    statement: "Robot bắt đầu tại (0,0), quay về hướng +y. Chuỗi command gồm R quay phải 90°, L quay trái 90°, G tiến một ô và B lùi một ô theo hướng hiện tại. Hãy xử lý command đúng thứ tự và trả tọa độ cuối [x,y].",
    officialLinks: [{ label: "PCCP 모의고사 #2 — 실습용 로봇", url: "https://school.programmers.co.kr/learn/courses/15009/lessons/121687?language=javascript", relation: "EXACT" }],
    input: ["command: chuỗi chỉ gồm R, L, G, B; các ký tự được xử lý từ trái sang phải.", "Hệ tọa độ dùng +x sang phải và +y hướng lên."],
    output: "Cặp [x,y] của robot sau khi thực hiện toàn bộ command.",
    examples: [{ input: `command="GRGRGRG"`, output: "[0,0]", explanation: "Robot đi bốn cạnh của một hình vuông và quay về origin." }],
  },
  "PT-F07-COLLISION-TIMELINE": {
    statement: "Mỗi robot đi qua một route gồm các point ID. Giữa hai waypoint, robot luôn đổi row từng ô cho tới khi đúng row rồi mới đổi column. Tất cả robot di chuyển đồng thời, bắt đầu tại time 0; robot hoàn thành route thì rời ngay. Một nguy cơ được tính cho mỗi cặp (time,coordinate) có ít nhất hai robot, bất kể có hai hay nhiều robot.",
    officialLinks: [{ label: "[PCCP 기출문제] 3번 — 충돌위험 찾기", url: "https://school.programmers.co.kr/learn/courses/30/lessons/340211?language=javascript", relation: "EXACT" }],
    input: ["points[id-1]=[row,col]: tọa độ của point ID 1-based.", "routes[robot]: dãy point ID robot phải đi qua theo thứ tự."],
    output: "Tổng số cell/time có ít nhất hai robot cùng hiện diện.",
    examples: [{ input: "points=[[0,0],[0,2]], routes=[[1,2],[2,1]]", output: "1", explanation: "Hai robot cùng ở (0,1) tại time 1; hai endpoint ở time 0 và 2 khác nhau." }],
  },
  "PT-F09-QUEUE-HEAD": {
    statement: "Các process nằm trong queue theo input order và mang priority. Lấy front: nếu còn process có priority cao hơn thì đưa current về tail; nếu không thì execute và loại khỏi queue. Hãy trả thứ tự execute 1-based của process ở original index location.",
    officialLinks: [{ label: "Programmers — 프로세스", url: "https://school.programmers.co.kr/learn/courses/30/lessons/42587?language=javascript", relation: "EXACT" }],
    input: ["priorities[i]: priority 1..9 của process original index i; duplicate được phép.", "location: original index của process mục tiêu."],
    output: "Thứ tự 1-based mà target process được execute.",
    examples: [{ input: "priorities=[2,1,3,2], location=2", output: "1", explanation: "Hai process đầu bị re-enqueue vì priority 3 còn tồn tại; target index 2 được execute đầu tiên." }],
  },
  "PT-F11-COMBINATION": {
    statement: "Cho mảng items và số k. Hãy sinh mọi cách chọn đúng k index khác nhau mà không xét thứ tự: selection dùng các index tăng dần, nên [a,b] và [b,a] không phải hai kết quả khác nhau. Giữ thứ tự enumeration theo input.",
    officialLinks: [{ label: "Bài official đối chiếu combination/permutation — 소수 찾기", url: "https://school.programmers.co.kr/learn/courses/30/lessons/42839?language=javascript", relation: "RELATED" }],
    input: ["items: mảng item distinct theo index.", "k: số item cần chọn; có thể bằng 0 hoặc lớn hơn items.length."],
    output: "Mảng combinations theo thứ tự DFS/start-index; mỗi combination là một mảng item.",
    examples: [{ input: "items=[1,2,3], k=2", output: "[[1,2],[1,3],[2,3]]", explanation: "start index tăng nghiêm ngặt loại các permutation đảo thứ tự." }],
  },
  "PT-OF036-TARGET-NUMBER": {
    statement: "Cho mảng numbers. Bạn phải dùng mọi phần tử đúng một lần và giữ nguyên thứ tự; trước mỗi số chọn dấu + hoặc -. Hãy đếm số cách gán dấu sao cho giá trị biểu thức bằng target. Hai cách khác nhau nếu có ít nhất một index nhận dấu khác.",
    officialLinks: [{ label: "Programmers — 타겟 넘버", url: "https://school.programmers.co.kr/learn/courses/30/lessons/43165?language=javascript", relation: "EXACT" }],
    input: ["numbers: mảng số nguyên không âm; mỗi index bắt buộc được dùng.", "target: tổng có dấu cần đạt."],
    output: "Số cách gán dấu +/− đạt đúng target.",
    examples: [{ input: "numbers=[1,1,1,1,1], target=3", output: "5", explanation: "Có 5 cách chọn đúng một số mang dấu trừ và bốn số mang dấu cộng." }],
  },
  "PT-OF022-FATIGUE": {
    statement: "Bạn có initialFatigue và danh sách dungeon [required,cost]. Chỉ được vào dungeon khi fatigue hiện tại >= required; sau khi hoàn thành, fatigue giảm đúng cost. Mỗi dungeon được vào tối đa một lần và bạn được tự chọn thứ tự. Hãy hoàn thành nhiều dungeon nhất.",
    officialLinks: [{ label: "Programmers — 피로도", url: "https://school.programmers.co.kr/learn/courses/30/lessons/87946?language=javascript", relation: "EXACT" }],
    input: ["initialFatigue: độ mệt mỏi ban đầu.", "dungeons[i]=[required,cost]: điều kiện vào và lượng fatigue bị trừ; thứ tự input không bắt buộc là thứ tự đi."],
    output: "Số dungeon tối đa có thể hoàn thành.",
    examples: [{ input: "initialFatigue=80, dungeons=[[80,20],[50,40],[30,10]]", output: "3", explanation: "Đi theo thứ tự 0→2→1: fatigue 80→60→50→10, nên hoàn thành cả ba." }],
  },
  "PT-OF023-POWER-GRID": {
    statement: "n trạm điện và n−1 dây nối tạo thành một cây vô hướng. Bạn phải cắt đúng một dây, làm mạng tách thành đúng hai component. Hãy chọn dây cắt để chênh lệch số trạm giữa hai component là nhỏ nhất.",
    officialLinks: [{ label: "Programmers — 전력망을 둘로 나누기", url: "https://school.programmers.co.kr/learn/courses/30/lessons/86971?language=javascript", relation: "EXACT" }],
    input: ["n: số node đánh số 1..n.", "wires: mảng n−1 cạnh [a,b]; thứ tự a,b không mang hướng và toàn bộ graph là tree."],
    output: "Giá trị nhỏ nhất của |size(componentA)−size(componentB)| sau khi cắt một wire.",
    examples: [{ input: "n=4, wires=[[1,2],[2,3],[3,4]]", output: "0", explanation: "Cắt 2–3 tạo hai component có cùng size 2." }],
  },
  "PT-OF057-INTERCEPTION": {
    statement: "Mỗi mục tiêu bay qua một interval mở (start,end) trên trục số. Một phát bắn tại tọa độ x chặn mọi mục tiêu có start < x < end; bắn đúng endpoint không chặn được mục tiêu đó. Hãy dùng ít phát nhất để chặn toàn bộ mục tiêu.",
    officialLinks: [{ label: "Programmers — 요격 시스템", url: "https://school.programmers.co.kr/learn/courses/30/lessons/181188?language=javascript", relation: "EXACT" }],
    input: ["targets[i]=[start,end] với start < end; mỗi interval là khoảng mở.", "Một shot có thể chặn nhiều interval cùng chứa tọa độ của shot."],
    output: "Số phát bắn tối thiểu.",
    examples: [{ input: "targets=[[1,4],[3,7],[5,12]]", output: "2", explanation: "Một shot ngay trước 4 chặn hai interval đầu; interval thứ ba cần shot khác." }],
  },
  "PT-OF043-IMMIGRATION-BIGINT": {
    statement: "Có nhiều quầy nhập cảnh; quầy i cần times[i] phút để xử lý một người và có thể xử lý liên tục. Tại thời gian T, quầy i xử lý được floor(T/times[i]) người. Hãy tìm thời gian nguyên nhỏ nhất để tổng số người đã xử lý đạt ít nhất people.",
    officialLinks: [{ label: "Programmers — 입국심사", url: "https://school.programmers.co.kr/learn/courses/30/lessons/43238?language=javascript", relation: "EXACT" }],
    input: ["people: số người cần xử lý, có thể rất lớn.", "times: mảng thời gian xử lý của các quầy; các quầy làm song song."],
    output: "Thời gian nhỏ nhất dưới dạng BigInt; arithmetic phải chính xác cả khi đáp án vượt Number.MAX_SAFE_INTEGER.",
    examples: [{ input: "people=6, times=[7,10]", output: "28n", explanation: "T=27 xử lý 3+2=5 người, còn T=28 xử lý 4+2=6; 28 là first feasible." }],
  },
  "PT-DFS-TAKE-SKIP": {
    statement: "Cho numbers gồm các số nguyên không âm. Với mỗi index, bạn được chọn lấy số đó hoặc bỏ qua; mỗi index chỉ được quyết định một lần và thứ tự chọn không tạo cách mới. Hãy đếm số subset theo index có tổng đúng target.",
    officialLinks: [{ label: "Bài official cùng cây quyết định — 타겟 넘버", url: "https://school.programmers.co.kr/learn/courses/30/lessons/43165?language=javascript", relation: "RELATED" }],
    input: ["numbers: mảng dài tối đa 20; các index trùng value vẫn là hai lựa chọn riêng.", "target: tổng cần đạt."],
    output: "Số subset theo index có tổng bằng target; subset rỗng được tính nếu target=0.",
    examples: [{ input: "numbers=[1,2,3], target=3", output: "2", explanation: "Hai subset là [3] và [1,2]." }],
  },
  "PT-BT-ASSIGNMENT": {
    statement: "Có n vị trí và n ứng viên. scores[position][candidate] là điểm nếu giao candidate đó cho position. Mỗi vị trí phải nhận đúng một ứng viên và mỗi ứng viên chỉ được dùng một lần. Hãy tối đa hóa tổng điểm.",
    officialLinks: [{ label: "PCCP 모의고사 #1 — 체육대회", url: "https://school.programmers.co.kr/learn/courses/15008/lessons/121684?language=javascript", relation: "EXACT" }],
    input: ["scores: ma trận vuông n×n, 1≤n≤9; điểm có thể âm."],
    output: "Tổng điểm lớn nhất của một phép gán one-to-one hoàn chỉnh.",
    examples: [{ input: "scores=[[9,8],[8,1]]", output: "16", explanation: "Greedy lấy 9 trước chỉ được tổng 10; phép gán chéo 8+8 đạt 16." }],
  },
};
